name: EternalChestShop
main: xyz.oribuin.chestshops.EternalChestShops
version: '@version@'
api-version: '1.16'
author: Oribuin
description: Create player owned shops on any container.
depend:
  - Vault
softdepend:
  - PlaceholderAPI